/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChartsDashboard: typeof import('./components/ChartsDashboard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SustainabilityData: typeof import('./components/SustainabilityData.vue')['default']
  }
}
